# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "task/enable-github-actions" ]
  pull_request:
    branches: [ "development" ]
    
permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph
  
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            preset: relwithdebinfo

    steps:
    - uses: actions/checkout@v4
      # Set up the MSVC environment for Windows builds
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Cache vcpkg
      id: cache-vcpkg
      # Cache the vcpkg build artifacts to speed up subsequent runs
      uses: actions/cache@v3
      with:
        path: |
          vcpkg/installed
          vcpkg/buildtrees
          vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Configure CMake using Presets
      # Configure the project using the specified CMake preset
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      # Build the project using the specified CMake preset
      run: cmake --build --preset ${{ matrix.preset }}

#    - name: Test
#      run: ctest --preset ${{ matrix.preset }} --output-on-failure
